[package]
name = "fortran-descriptor-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
fortran-descriptor-parser-macro = { path = "../fortran-descriptor-parser-macro", version = "0.1.0" }
lexical = "7.0.4"
thiserror = "2.0.11"
