name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Rust toolchain
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      # Install nextest
      - name: Install cargo-nextest
        uses: taiki-e/install-action@cargo-nextest

      # Run Clippy (linting)
      - name: Run Clippy
        run: cargo clippy --all-targets -- -D warnings

      # Check code formatting
      - name: Check formatting
        run: cargo fmt --all --check

      # Run tests with cargo-nextest
      - name: Run Tests
        run: cargo nextest run

